//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppOreshnikov.Application_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_Entities : DbContext
    {
        private static bd_Entities _context;

        public static bd_Entities Get_Context()
        {
            if (_context == null) _context = new bd_Entities();
            return _context;
        }

        public bd_Entities()
            : base("name=bd_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<polzovateli> polzovateli { get; set; }
        public virtual DbSet<Roli> Roli { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<sklad> sklad { get; set; }
    }
}
