//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppOreshnikov.Application_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sklad
    {
        public string artikul { get; set; }
        public string naimemovanie { get; set; }
        public string ed_izmereniya { get; set; }
        public decimal stoimost { get; set; }
        public decimal vozmojnaya_skidka { get; set; }
        public string proizvoditel { get; set; }
        public string postavsik { get; set; }
        public string kategoriya { get; set; }
        public decimal skidka { get; set; }
        public int kolichestvo { get; set; }
        public string opisanie { get; set; }
        public string izobrajenie { get; set; }
    }
}
